USE [master]
GO

/****** Object:  Database [Orders]    Script Date: 04/29/2019 23:17:22 ******/
CREATE DATABASE [Orders] ON  PRIMARY 
( NAME = N'Orders', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Orders.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Orders_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Orders_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Orders] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Orders].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Orders] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Orders] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Orders] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Orders] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Orders] SET ARITHABORT OFF 
GO

ALTER DATABASE [Orders] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Orders] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Orders] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Orders] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Orders] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Orders] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Orders] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Orders] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Orders] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Orders] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Orders] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Orders] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Orders] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Orders] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Orders] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Orders] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Orders] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Orders] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Orders] SET  READ_WRITE 
GO

ALTER DATABASE [Orders] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Orders] SET  MULTI_USER 
GO

ALTER DATABASE [Orders] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Orders] SET DB_CHAINING OFF 
GO


